apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudcommerce-frontend
  template:
    metadata:
      labels:
        app: cloudcommerce-frontend
    spec:
      containers:
        - name: frontend
          image: cloudcommerce-frontend:latest
          imagePullPolicy: Never  # Use local images
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcommerce-frontend
spec:
  selector:
    app: cloudcommerce-frontend
  ports:
    - port: 80
      targetPort: 80


