apiVersion: v1
kind: ServiceMonitor
metadata:
  name: cloudcommerce-backend-monitor
  labels:
    app: cloudcommerce-backend
spec:
  selector:
    matchLabels:
      app: cloudcommerce-backend
  endpoints:
  - port: http
    path: /health
    interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcommerce-backend-metrics
  labels:
    app: cloudcommerce-backend
spec:
  selector:
    app: cloudcommerce-backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudcommerce-backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mongo:6
            command:
            - /bin/bash
            - -c
            - |
              mongodump --host=cloudcommerce-mongo:27017 --out=/backup/$(date +%Y%m%d)
              tar -czf /backup/backup-$(date +%Y%m%d).tar.gz /backup/$(date +%Y%m%d)
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure