apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudcommerce-mongo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/cloudcommerce-mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudcommerce-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

